apiVersion: v1
kind: Service
metadata:
  name: django-app-cluster
  namespace: app-deployment
spec:
  type: ClusterIP
  selector:
    app: django-todo
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

