apiVersion: v1
kind: Service
metadata:
  name: my-django-app-loadbalancer
  namespace: app-deployment
spec:
  selector:
    app: django-todo
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
