apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: app-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

