apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: app-deployment
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do wget -q -O- django-app-cluster:8000; done']
